### ISSUE TITLE
Show essay-ID in editor

### ISSUE THREAD

**Issue by cajosc** [spraakbanken/swell-editor#101]
Show current essay-ID in the editor, e.g. in the header. Note that there is no essay-ID when the editor is used standalone.

**Comment by arildm** [comment]
It is already showing in the footer.

Here, it is `ST4SH`:

<img width="922" alt="screenshot 2018-11-18 at 21 53 26" src="https://user-images.githubusercontent.com/1454404/48677931-6b17e400-eb7c-11e8-9261-4456069b5f52.png">
