### ISSUE TITLE
Pseudonymization for age_string

### ISSUE THREAD

**Issue by arildm** [spraakbanken/swell-editor#106]
Continued from #74 

> we need to consider how to handle the replacement. Maybe add an option to manually add a number in digits (the original age for intermediate span calculation), or directly a span? E.g. for "Jag är arton år" we replace "arton" with @age_string:15-21 - or something like that? What is feasible to do?

**Comment by cajosc** [comment]
Why not edit source text, replace "arton" with the number 18 and then add label?

**Comment by elenavolodina** [comment]
If we let assistants replace an age-string with a number, but label with < age-string > - could we maybe render the same way as in < age-number > but spell the number out? This way the rendered text would correspond to the original better.

**Comment by arildm** [comment]
Fixed in 2bf27e4. Now, the numeric label is interpreted differently for `age_string`. The number generated will be close to the numeric label.

![Screenshot 2019-04-18 at 10 30 45](https://user-images.githubusercontent.com/1454404/56347753-42485900-61c5-11e9-941b-9f5968c7f9f7.png)

Not pushed to kiosk yet.

**Comment by arildm** [comment]
Now pushed to kiosk

**Comment by arildm** [comment]
- [ ] Should not keep the original age as a label

**Comment by arildm** [comment]
Suggestion: add a "pseudonymization argument" widget where the user can enter the numeric age

**Comment by arildm** [comment]
The new solution replaces the function of the input field, if `age_string` has been added, so that any number entered is *not* used as another label, but only as an argument to the pseudonymizer.

With the following example, test it by dragging the image into the [dev](https://spraakbanken.gu.se/swell/dev/#start_mode=anonymization) instance of the editor, selecting the "arton" edge, adding the `age_string` label and then entering "18" in the "Extra input" field.

![](https://ws.spraakbanken.gu.se/ws/swell/png?mode%3Aanon%20Jag%20heta%20Peter%20jag%20arton%20%C3%A5r%20.%2F%2FJag%20heta%20Peter%20jag%20arton%20%C3%A5r%20.)

**Comment by elenavolodina** [comment]
This is perfect! I like the solution - very easy and elegant! Did you push it to kiosk? We need also to inform Lisa for her pseudonymization work.

Some comments:
1. Dragging exe did not work for me - can we test that together? 
2. By handling < age-string > that way we do not add a numeric label to the anonymization label, but this is probably not important...

**Comment by elenavolodina** [comment]
@arildm Could you, please, replace all mentions of "anonymization" with "pseudonymization" in the Svala-tool? 

- in the view name (Svala pseudonymization)
- in the link (menu on the right)
- in the link to guidelines (menu on the right)

**Comment by arildm** [comment]
I will check with Lisa.

I created #152 (drag-and-drop bug) and #151 ("pseudonymization") as follow-ups from your comments, @elenavolodina.
