### ISSUE TITLE
Got source text from another essay

### ISSUE THREAD

**Issue by arildm** [spraakbanken/swell-editor#110]
During demo at SweLL meeting today, in normalization mode, when enabling the source text editor, it showed the text from an essay that had been edited previously. Going back and re-opening fixed it.

Was it fetched from browser local storage? Prevent this.

**Comment by elenavolodina** [comment]
Got the same today (in Safari, in correction annotation mode)

![skarmavbild 2019-01-14 kl 13 06 42](https://user-images.githubusercontent.com/31984909/51111828-a8f05c00-17fd-11e9-85be-edc943a5a189.png)


Didn't see an option to open the target text from the "option menu". We said that there shouldn't be possible to change the target, but to see the difference and being able to read through both should probably be necessary at some point.

**Comment by elenavolodina** [comment]
There is a side effect that source/target texts cannot be clickable in the correction annotation mode: Long texts are then given as one big chunk of spaghetti, not sentence by sentence. Please, look at the essay B1BT1, I have just assigned that essay to Arild for correction annotation for testing (go via portal).

**Comment by arildm** [comment]
Lisa has had this error on kiosk recently. The [`fix-wrong-source`](https://github.com/spraakbanken/swell-editor/tree/fix-wrong-source) branch contains two potential fixes. The first was pushed to kiosk and to [/swell/dev](https://spraakbanken.gu.se/swell/dev/), but Mats noted that the problem persists, so I commited the second one just now. It is on /swell/dev but not on kiosk (yet).
