### ISSUE TITLE
Separate normalization and error annotation

### ISSUE THREAD

**Issue by cajosc** [spraakbanken/swell-editor#116]
See spraakbanken/swell-portal#29.

**Comment by arildm** [comment]
In the source code, error annotation is quite thoroughly included in the normalization mode, and separating those would probably be size:L. But I'm sure there's a way to make it *appear* as two different modes without too much refactoring.

**Comment by arildm** [comment]
I have made some progress with this on the [correctannot](https://github.com/spraakbanken/swell-editor/tree/correctannot) branch.

From discussion with @elenavolodina, it seems like this affects the lifecycle of an essay in the Swell Portal. Probably, an essay should be anonymized by 1 annotator, **normalized by 1 annotator** and then correction-annotated by multiple annotators.

@cajosc Will this affect the API? Should a save request be different depending on the mode?

**Comment by elenavolodina** [comment]
Vi pratade igår med Arild att ta några beslut om tillstånd i normalisering versus felannotering. Jag har nu pratat med Gunlög Sundberg, och vårt förslag är följande:

Normalisering ska göras på hela texter (inte på mening-till-mening basis) och sparas utan någon validering. Man bör ha en möjlighet/frihet att fixa länkar om man vill, men inget krav. Man ska också kunna gå in i anonymiseringsläge under detta steg och ändra där.

Felannotering - då behöver man fixa länkar och sätta på etiketter där det finns skillnad mellan original och target, samt där länkarna är manuella. Validering bör kopplas på i detta steg. Vi förstår så att i detta steg bör man inte kunna ändra i target text längre, men att gå tillbaka och sätta en anonymiseringsetikett bör kanske ändå gå att få till?

**Comment by arildm** [comment]
This is now ready on the editor side.
