### ISSUE TITLE
Swapping between modes in online SVALA

### ISSUE THREAD

**Issue by elenavolodina** [spraakbanken/swell-editor#123]
After changing from anonymisation to normalisation modes, the numbering from anonymisation is kept in the area to the right, see the image. I do not think it should be there:

![skarmavbild 2019-01-15 kl 15 19 51](https://user-images.githubusercontent.com/31984909/51186113-1d4bfd80-18d9-11e9-92ce-b7656391a790.png)

@arildm

**Comment by arildm** [comment]
This sidebar is now only visible in anonymization mode.
