### ISSUE TITLE
Faster

### ISSUE THREAD

**Issue by arildm** [spraakbanken/swell-editor#124]
Normalization users reported that the tool is slow, independently on essay size.

* Test-run on lower RAM and CPU
* Be on the look-out for potential code optimizations

**Comment by danr** [comment]
Chrome has a pretty good profiler, I can show it tomorrow. This is useful to find bottlenecks.

**Comment by arildm** [comment]
The `G.enrichen` operation is a bit expensive, and it was called on every redraw, including when hovering over the spaghetti. Since 7aca1d1, the `G.enrichen` result is cached in the app state, and only recalculated when needed (i.e. a label is added/removed, the text is edited or edges are modified). It should be a bit faster now.
