### ISSUE TITLE
Spaghetti selection is sometimes reset

### ISSUE THREAD

**Issue by arildm** [spraakbanken/swell-editor#138]
Happened several times during joint error annotation in Umeå, on Lisa's computer, with quite a long essay, B10BT1.

Scenario: Target text visible and not resized. Spaghetti not resized. Selecting spaghetti links, adding labels, pressing "next mod". Sometimes, when clicking in the label sidekick (adding a label or just scrolling by clicking the scrollbar), the UI freezes for 1-3 seconds, and then the selection is lost and the full spaghetti is displayed.

Very disruptive to workflow.

I cannot reproduce on my computer.

**Comment by elenavolodina** [comment]
![m-def](https://user-images.githubusercontent.com/31984909/51999812-e6224280-24bb-11e9-9d09-dc5fa053c8fa.png)

**Comment by arildm** [comment]
A hunch: some kind of resource overflow. Perhaps optimization (#124) is needed.

It seems to happen when mouse leaves spaghetti. I timed the `onMouseLeave` on the `<ul>`s in the spaghetti and got > 1s.

    onMouseLeave={() => console.log(Utils.timeit('gv-mouseleave', () => on_hover(undefined)))}>

**Comment by arildm** [comment]
Cause found: In bc66431 I introduced that clicking a selected edge causes it to be deselected. In turn, this resets the subspan, and so the whole graph is rendered. This takes a few seconds for a long essay, which causes the UI to freeze.

**Comment by arildm** [comment]
With e8938ca, clicking the selected edge does not deselect it, so we don't get the freeze-up when the full spaghetti is rendered.

55d4e8e adds a "show full graph" button in options menu.
