### ISSUE TITLE
HTTP status code 204 treated as error

### ISSUE THREAD

**Issue by cajosc** [spraakbanken/swell-editor#140]
https://github.com/spraakbanken/swell-editor/blob/791e200f191dbbf6c360b34f8e63f8c8b7ff21f1/src/Utils.ts#L877-L884

`.../report` returns 204 which is wrongfully treated as an error by the editor (see e.g. https://en.wikipedia.org/wiki/List_of_HTTP_status_codes).

**Comment by arildm** [comment]
Oops. I fixed this in 7995c67 but then accidentally restored it when refactoring POST and GET in 0959362. Now fixed _again_ in b4a19b8
