### ISSUE TITLE
Revise transcription during pseudonymization step

### ISSUE THREAD

**Issue by arildm** [spraakbanken/swell-editor#145]
To correct transcription mistakes, we can consider editing of the source text in the anonymization mode. Maybe with a warning like "Are you sure?" How much are you allowed to edit, e.g. whole text, same sentence or just a token?

**Comment by lisarudebeck** [comment]
Jag tror inte att detta är den bästa lösningen. Behov av att rätta i transkriptionerna uppstår väldigt sällan, men när de uppstår handlar det i regel om stora korrigeringar, t.ex. att en och samma fil i själva verket innehåller två olika texter eller att en fil i själva verket är en kopia av en annan fil med ett annat namn. Jag tror alltså att det som behövs snarare är en möjlighet att ta bort importerade transkriptioner och att ersätta dem med nya.

**Comment by arildm** [comment]
Closing in favor of spraakbanken/swell-portal#65 *Delete anonymization to allow re-import in kiosk*
