### ISSUE TITLE
Anonymization of multi-word sequences

### ISSUE THREAD

**Issue by cajosc** [spraakbanken/swell-editor#69]
![](https://ws.spraakbanken.gu.se/ws/swell/png?mode%3Aanon%20Jag~Jag%20pluggade~pluggade%20p%C3%A5~p%C3%A5%20Sigrid~Sigrid%3Aschool%20Rudebecks~Rudebecks%3Aschool%20gymnasium.~gymnasium.%3Aschool%2F%2FJag~Jag%20pluggade~pluggade%20p%C3%A5~p%C3%A5%20school~Sigrid%20school~Rudebecks%20school~gymnasium.)

`school` should be grouped, i.e.

![](https://ws.spraakbanken.gu.se/ws/swell/png?mode%3Aanon%20Jag~Jag%20pluggade~pluggade%20p%C3%A5~p%C3%A5%20Sigrid~Sigrid%3Aschool%20Rudebecks~Sigrid%20gymnasium.~Sigrid%2F%2FJag~Jag%20pluggade~pluggade%20p%C3%A5~p%C3%A5%20school~Sigrid)

**Comment by arildm** [comment]
Done in 71d20af and ea39db2.

Now if you select multiple tokens and add a tag, the tokens will be grouped.

![screen shot 2018-10-12 at 07 34 54](https://user-images.githubusercontent.com/1454404/46850143-f9b57a80-cdf2-11e8-8ca7-5adca02ad57c.png) ... becomes ... ![screen shot 2018-10-12 at 07 35 12](https://user-images.githubusercontent.com/1454404/46850145-fae6a780-cdf2-11e8-95a5-8a7734c736fe.png)

Note that tokens are grouped even if they are not consecutive, so if I select "Alice" and "Alice's" and then set a tag, then this will happen:

![screen shot 2018-10-12 at 07 47 54](https://user-images.githubusercontent.com/1454404/46850185-29fd1900-cdf3-11e8-8c06-48daec6aec3e.png)

This is probably not useful, but it is the easiest way to do this. If it is a requirement, we can also check for consecutive-ness.

**Comment by elenavolodina** [comment]
The first example is perfect! 
The second one is slightly problematic since we want to add a "genitive case" tag to the "firstname:female" tag for Alice's. 

But I think this should be tested first before changing

**Comment by arildm** [comment]
Fixed this, so the second case (in my last comment) will not happen. Edges will only be grouped if their tokens are consecutive.

**Comment by elenavolodina** [comment]
A bug (in online SVALA, anonymiation mode):

![skarmavbild 2019-01-14 kl 18 30 55](https://user-images.githubusercontent.com/31984909/51129450-c1c33680-182a-11e9-9fca-8696865b7ac8.png)

The word "develooper" has come up 3 times in the "target" version

**Comment by arildm** [comment]
This is now fixed.
