### ISSUE TITLE
Link to code book and guidelines from the editor

### ISSUE THREAD

**Issue by cajosc** [spraakbanken/swell-editor#72]

**Comment by elenavolodina** [comment]
Anonymization guidelines (to kiosk version): https://github.com/spraakbanken/swell-project/blob/master/Anonymization_guidelines.md

Transcription guidelines (to kiosk version): https://github.com/spraakbanken/swell-project/blob/master/Transcription_guidelines.md

**Comment by arildm** [comment]
Is Svala used for transcription? In which mode?

**Comment by cajosc** [comment]
Not that I know of. There's a separate tool (https://github.com/spraakbanken/swell-transcription) that's meant to be used on the kiosks.
