### ISSUE TITLE
Rendering of numerical information in anonymization 

### ISSUE THREAD

**Issue by elenavolodina** [spraakbanken/swell-editor#74]
Replace target strings directly for the following categories: 

* personal names - initials and middlenames
* geographic data - zip-code
* age
* dates
* phone numbers
* social security numbers
* account numbers
* certificate/license numbers

The pseudonymization principles are described in the anonymization guidelines where the relevant  categories are marked in yellow :

https://docs.google.com/document/d/1oLi96zpHTrhlnkCvOwBA3evo_7Ya9v-BwGfYji7-auE/edit#

**Comment by elenavolodina** [comment]
There is a complication, though: if for example age is written in letters (and also misspelled, like "niotton" or "sIxtton"), then automatic replacement becomes nontrivial. We need to have an option to add "pseudonimyzation" manually the tool by rewriting the target token. At the moment this is not possible.

**Comment by elenavolodina** [comment]
Our updated anonymization guidelines: 
https://github.com/spraakbanken/swell-project/blob/master/Anonymization_guidelines.md

I am looking into your questions. Will come back asap

**Comment by elenavolodina** [comment]
Some details are in the notes from the last meeting, on page 4-5 under "1. Anonymization":
https://spraakbanken.gu.se/sites/spraakbanken.gu.se/files/Minnesanteckningar_SweLL_Projektmote_20180830-31.pdf

As for the different types of dates - since these may take various forms, please add a category "date_nr" which will be treated as a number sequence that will be replaced with a standard number, e.g. "1" - number for number, with preservation of all delimiters, e.g.   
* 2018-12-01 --> @date_nr --> 1111-11-11
* 18/01/12 -->  @date_nr -->11/11/11 
*180112 --> @date_nr -->111111
*18.01.12 --> @date_nr -->11.11.11

This way we will have a @placeholder-tag for "date-nr" and a "hard" replacement of the original numbers. 

Also, please add to "Misc"(ellaneous) category "other_nr_seq"(uence) to cover other unforeseen sequences of numbers. They should also be replaced during the anonymization stage  with some standard number (e.g. 0), number for number, keeping all original delimiters. 

All those "hard" replacements that need to be done right away should probably be done as a "suggestion" first, and replaced forever on pushing "Done" button.... here we need to think about the procedure...


"Age" is another category that may take various forms - numbers, letters, so please add (instead of just "age":
* "age_digits", 
* "age_string".  
For @age_string we need to consider how to handle the replacement. Maybe add an option to manually add a number in digits (the original age for intermediate span calculation), or directly a span? E.g. 
* for  "Jag är arton år" we replace "arton" with @age_string:15-21 - or something like that? What is feasible to do?

**Comment by arildm** [comment]
age_string is tricky, so I've moved that to an issue of its own: #106

Other than that, all of this is done.

**Comment by arildm** [comment]
age_string is tricky, so I've moved that to an issue of its own: #106

Other than that, all of this is done.

**Comment by arildm** [comment]
age_string is tricky, so I've moved that to an issue of its own: #106

Other than that, all of this is done.
