### ISSUE TITLE
Unmark all marked tokens on clicking outside spaghetti or on a new token

### ISSUE THREAD

**Issue by elenavolodina** [spraakbanken/swell-editor#81]
We have been discussing whether we should give the chance to mark multiple tokens. It seems to cause more errors than to help, so for now the suggestion is to mark only one token that is clicked on. How to mark multiple ones should be discussed separately, maybe like in all other editors by holding "command"/"alt" and clicking? 

That is, 
1. unmark everything when clicked outside the spaghetti and 
2. mark only the one that is clicked on
3. mark several only if "command" or some other key is pressed at the same time

**Comment by arildm** [comment]
Fixed in f85fdcb
