### ISSUE TITLE
Scrollbar spaghetti area

### ISSUE THREAD

**Issue by elenavolodina** [spraakbanken/swell-editor#88]
At times spaghetti-area can be very long, and to see the target hypothesis and/or the original text areas is impossible, though often necessary. In the example below, the word "Det" in the spaghetti corresponds to the "Det" in the target hypothesis area, but it is impossible to see the original text area

![](https://spraakbanken.gu.se/sites/spraakbanken.gu.se/files/Scrollbar_spaghetti.png)

**Comment by arildm** [comment]
I have removed the fixed width, so on large-enough screens the editor and spaghetti area will be wider. I have also removed the fixed height for the text editors, so they will be shorter if the text is shorter. This should provide better overview.
