### ISSUE TITLE
Edit source text in editor

### ISSUE THREAD

**Issue by elenavolodina** [spraakbanken/swell-editor#89]
When the original (pre-anonymized) text is tokenized, certain sentence boundaries are impossible to automatically detect. So, it is important that we at some stage can edit the original text. At the moment it is impossible, and hence we get real spaghetti, like "...barn.Men"  below:

![](https://spraakbanken.gu.se/sites/spraakbanken.gu.se/files/Sentence_segmentation.png)

Instead of just assuming that the text is correct, we need to indicate that this is not a single token, it has to be split, and also split into two sentences... 

A solution would be a possibility to edit the original text - with some severe limitations as to what can be changed, e.g. only spaces can be added... This needs further thought.

**Comment by arildm** [comment]
I have made it possible to add/remove whitespace in the source text.
