### ISSUE TITLE
Add help text to the editor

### ISSUE THREAD

**Issue by cajosc** [spraakbanken/swell-editor#94]
- [x] spraakbanken/swell-editor#72
- [x] spraakbanken/swell-editor#20 (postponed as of https://github.com/spraakbanken/swell-editor/issues/20#issuecomment-453511747)

**Comment by arildm** [comment]
Pull raw Markdown files directly and render in-line.

**Comment by arildm** [comment]
> Pull raw Markdown files directly and render in-line.

That may be possible with some kind of auth token, not sure. The current solution instead grabs the HTML from the GitHub pages, e.g. https://spraakbanken.github.io/swell-project/Anonymization_guidelines

**Comment by elenavolodina** [comment]
Looks good to me
