### ISSUE TITLE
Generate numbers for replacements in editor

### ISSUE THREAD

**Issue by cajosc** [spraakbanken/swell-editor#96]
- [x] Sequential for same type.
- [x] Same if strings match (fuzzy/substring?).

**Comment by arildm** [comment]
> * Sequential for same type.

If I understand the guildelines correctly, it should actually be sequential over all types. So if I have `city 1` already, then when I mark something as `area` it should be `2`, not `1` again.

This is now implemented. But not the second point, about matching against previously numbered tokens.

**Comment by arildm** [comment]
Matching implemented in e1982c7
